### ISSUE TITLE
An internal DaCe error was encountered! (DaCe request failed with code 500)

### ISSUE THREAD

**Issue by HappyCockroach** [spcl/dace-vscode#129]
I'm working under Windows and using remote-SSH to remotely connect to my Linux server. 
After installing DaCe-vscode on the server, there is an error. Does this affect the use of DaCe-vscode?
```
An internal DaCe error was encountered! (DaCe request failed with code 500)
```
![image](https://user-images.githubusercontent.com/80052401/129998459-2e92fa74-9eac-474d-bc6f-47ff8a5561c2.png)

**Comment by tbennun** [comment]
Thanks for reporting! We would need more context to understand the issue. If you open the terminal pane, a tab called "SDFG Optimizer" should be open there. What is the output log there?

**Comment by HappyCockroach** [comment]
The output log is:
```python
/home/chenzhiqiang/anaconda3/bin/python /home/chenzhiqiang/.vscode-server/extensions/phschaad.sdfv-1.0.3/backend/run_dace.py -p 9604
(base) chenzhiqiang@GEM02_GPU:~/code-repo/dace$ /home/chenzhiqiang/anaconda3/bin/python /home/chenzhiqiang/.vscode-server/extensions/phschaad.sdfv-1.0.3/backend/run_dace.py -p 9604
 * Serving Flask app "DaCeInterface" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[2021-08-19 20:32:14,727] INFO in _internal:  * Running on http://127.0.0.1:9604/ (Press CTRL+C to quit)
[2021-08-19 20:32:16,320] INFO in _internal: 127.0.0.1 - - [19/Aug/2021 20:32:16] "GET / HTTP/1.1" 200 -
[2021-08-19 20:32:16,337] ERROR in app: Exception on /get_metadata [GET]
Traceback (most recent call last):
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chenzhiqiang/.vscode-server/extensions/phschaad.sdfv-1.0.3/backend/run_dace.py", line 285, in _get_metadata
    return get_property_metdata()
  File "/home/chenzhiqiang/.vscode-server/extensions/phschaad.sdfv-1.0.3/backend/run_dace.py", line 67, in get_property_metdata
    from dace.sdfg.nodes import full_class_path
ImportError: cannot import name 'full_class_path' from 'dace.sdfg.nodes' (/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/dace/sdfg/nodes.py)
[2021-08-19 20:32:16,341] INFO in _internal: 127.0.0.1 - - [19/Aug/2021 20:32:16] "GET /get_metadata HTTP/1.1" 500 -
[2021-08-19 20:32:16,465] INFO in _internal: 127.0.0.1 - - [19/Aug/2021 20:32:16] "POST /transformations HTTP/1.1" 200 -
[2021-08-19 20:32:39,148] ERROR in app: Exception on /get_metadata [GET]
Traceback (most recent call last):
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chenzhiqiang/.vscode-server/extensions/phschaad.sdfv-1.0.3/backend/run_dace.py", line 285, in _get_metadata
    return get_property_metdata()
  File "/home/chenzhiqiang/.vscode-server/extensions/phschaad.sdfv-1.0.3/backend/run_dace.py", line 67, in get_property_metdata
    from dace.sdfg.nodes import full_class_path
ImportError: cannot import name 'full_class_path' from 'dace.sdfg.nodes' (/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/dace/sdfg/nodes.py)
[2021-08-19 20:32:39,150] INFO in _internal: 127.0.0.1 - - [19/Aug/2021 20:32:39] "GET /get_metadata HTTP/1.1" 500 -
[2021-08-19 20:32:39,152] ERROR in app: Exception on /get_metadata [GET]
Traceback (most recent call last):
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chenzhiqiang/.vscode-server/extensions/phschaad.sdfv-1.0.3/backend/run_dace.py", line 285, in _get_metadata
    return get_property_metdata()
  File "/home/chenzhiqiang/.vscode-server/extensions/phschaad.sdfv-1.0.3/backend/run_dace.py", line 67, in get_property_metdata
    from dace.sdfg.nodes import full_class_path
ImportError: cannot import name 'full_class_path' from 'dace.sdfg.nodes' (/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/dace/sdfg/nodes.py)
[2021-08-19 20:32:39,155] INFO in _internal: 127.0.0.1 - - [19/Aug/2021 20:32:39] "GET /get_metadata HTTP/1.1" 500 -
[2021-08-19 20:32:53,336] ERROR in app: Exception on /get_metadata [GET]
Traceback (most recent call last):
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chenzhiqiang/.vscode-server/extensions/phschaad.sdfv-1.0.3/backend/run_dace.py", line 285, in _get_metadata
    return get_property_metdata()
  File "/home/chenzhiqiang/.vscode-server/extensions/phschaad.sdfv-1.0.3/backend/run_dace.py", line 67, in get_property_metdata
    from dace.sdfg.nodes import full_class_path
ImportError: cannot import name 'full_class_path' from 'dace.sdfg.nodes' (/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/dace/sdfg/nodes.py)
[2021-08-19 20:32:53,338] ERROR in app: Exception on /get_metadata [GET]
Traceback (most recent call last):
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chenzhiqiang/.vscode-server/extensions/phschaad.sdfv-1.0.3/backend/run_dace.py", line 285, in _get_metadata
    return get_property_metdata()
  File "/home/chenzhiqiang/.vscode-server/extensions/phschaad.sdfv-1.0.3/backend/run_dace.py", line 67, in get_property_metdata
    from dace.sdfg.nodes import full_class_path
ImportError: cannot import name 'full_class_path' from 'dace.sdfg.nodes' (/home/chenzhiqiang/anaconda3/lib/python3.8/site-packages/dace/sdfg/nodes.py)
[2021-08-19 20:32:53,340] INFO in _internal: 127.0.0.1 - - [19/Aug/2021 20:32:53] "GET /get_metadata HTTP/1.1" 500 -
[2021-08-19 20:32:53,342] INFO in _internal: 127.0.0.1 - - [19/Aug/2021 20:32:53] "GET /get_metadata HTTP/1.1" 500 -
```
Is that the information you need?

**Comment by tbennun** [comment]
Yes, this helps! To check if it's a compatibility issue with releases, could you please try using the latest master branch of `dace` ?

To do so, please run `pip install --upgrade git+https://github.com/spcl/dace`

**Comment by HappyCockroach** [comment]
Yes, it is a compatibility issue with releases.
Probably because of the network, I can't run the command you provided, the error message is:
```python
(base) chenzhiqiang@GEM02_GPU:~$ pip install --upgrade git+https://github.com/spcl/dace
Collecting git+https://github.com/spcl/dace
  Cloning https://github.com/spcl/dace to /tmp/pip-req-build-hvxwslps
  Running command git clone -q https://github.com/spcl/dace /tmp/pip-req-build-hvxwslps
  git: 'remote-https' is not a git command. See 'git --help'.
WARNING: Discarding git+https://github.com/spcl/dace. Command errored out with exit status 128: git clone -q https://github.com/spcl/dace /tmp/pip-req-build-hvxwslps Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q https://github.com/spcl/dace /tmp/pip-req-build-hvxwslps Check the logs for full command output.
```

I downloaded the master branch source code for dace, `python setup.py install`, Installation via source code.
After successfully updating the dace, this problem did not appear anymore.

**Comment by tbennun** [comment]
Thank you for the update! We will make a release very soon and set the required version so that this does not happen again.
